definitions:
  models.Album:
    properties:
      artist:
        type: string
      id:
        type: integer
      price:
        type: number
      title:
        type: string
    type: object
  models.AlbumProps:
    properties:
      artist:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
  models.Error:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /albums:
    get:
      description: returns a list of albums
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Album'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: returns a list of albums
      tags:
      - albums
    post:
      description: creates a new album
      parameters:
      - description: album properties
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AlbumProps'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Album'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: creates a new album
      tags:
      - albums
  /albums/{id}:
    get:
      description: returns a album by its id
      parameters:
      - description: album id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Album'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: returns a album by its id
      tags:
      - albums
    put:
      description: updates an album
      parameters:
      - description: album id
        in: path
        name: id
        required: true
        type: integer
      - description: album properties
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AlbumProps'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Album'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: updates an album
      tags:
      - albums
swagger: "2.0"
