definitions:
  users.PostBody:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  users.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    post:
      description: creates a new user
      parameters:
      - description: album properties
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.PostBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/users.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: creates a new user
      tags:
      - users
swagger: "2.0"
