CREATE TABLE IF NOT EXISTS users (
  id        BIGSERIAL NOT NULL PRIMARY KEY,
  email     TEXT      NOT NULL UNIQUE,
  password  TEXT      NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
